### ISSUE TITLE
What are these licenses for?

### ISSUE THREAD

**Issue by runtimevic** [twincatlicense/twincat3-license#1]
Hello
What are these licenses for?... Are all licenses licensed forever?

**Comment by twincatlicense** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        for beckhoff  twincat3 
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/16/2022 03:36
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [twincatlicense/twincat3-license] What are these licenses for? (Issue #1)
        
      
    
  
  
Hello
What are these licenses for?

**Comment by twincatlicense** [comment]
> Hello What are these licenses for?... Are all licenses licensed forever?


There are three license modes:
1.Long-term trial license,   status display:expires on Aug 16,2022(trial license)
2.expire time license , status display:expires on Aug 16,2022
3.valid license,    status display:valid
